export const EU_SERVER_LIST = [
  "Amnennar",
  "Ashbringer",
  "Auberdine",
  "Bloodfang",
  "Celebras",
  "Chromie",
  "Dragon's Call",
  "Dragonfang",
  "Dreadmist",
  "Earthshaker",
  "Everlook",
  "Finkle",
  "Firemaw",
  "Flamegor",
  "Flamelash",
  "Gandling",
  "Gehennas",
  "Golemagg",
  "Harbinger of Doom",
  "Heartstriker",
  "Hydraxian Waterlords",
  "Judgement",
  "Lakeshire",
  "Lucifron",
  "Mandokir",
  "Mirage Raceway",
  "Mograine",
  "Nethergarde Keep",
  "Noggenfogger",
  "Patchwerk",
  "Pyrewood Village",
  "Razorfen",
  "Razorgore",
  "Rhok'delar",
  "Shazzrah",
  "Skullflame",
  "Stonespine",
  "Sulfuron",
  "Ten Storms",
  "Transcendence",
  "Venoxis",
  "Wyrmthalak",
  "Zandalar Tribe",
];

export const NA_SERVER_LIST = [
  "Anathema",
  "Arcanite Reaper",
  "Arugal",
  "Ashkandi",
  "Atiesh",
  "Azuresong",
  "Benediction",
  "Bigglesworth",
  "Blaumeux",
  "Bloodsail Buccaneers",
  "Deviate Delight",
  "Earthfury",
  "Faerlina",
  "Fairbanks",
  "Felstriker",
  "Grobbulus",
  "Heartseeker",
  "Herod",
  "Incendius",
  "Kirtonos",
  "Kromcrush",
  "Kurinnaxx",
  "Loatheb",
  "Mankrik",
  "Myzrael",
  "Netherwind",
  "Old Blanchy",
  "Pagle",
  "Rattlegore",
  "Remulos",
  "Skeram",
  "Smolderweb",
  "Stalagg",
  "Sul'thraze",
  "Sulfuras",
  "Thalnos",
  "Thunderfury",
  "Westfall",
  "Whitemane",
  "Windseeker",
  "Yojamba",
];
